import type { GalleryCollection, GalleryItem } from "@/features/ascii-engine/gallery/types";

const CLASSIC = " .:-=+*#%@";
const BLOCKS = " ░▒▓█";
const DENSE = ".'`^\",:;Il!i><~+_-?][}{1)(|\\/tfjrxnuvczXYUJCLQ0OZmwqpdbkhao*#MW&8%B@$";

/** 12 artes mock — categorias variadas; algumas com recipeId para remix. */
export const MOCK_GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "gal-root-mark",
    title: "Root Mark",
    author: "studio",
    charset: CLASSIC,
    cols: 11,
    rows: 5,
    tags: ["logo", "brand", "minimal"],
    category: "logos",
    recipeId: "phosphor",
    collectionIds: ["col-featured", "col-terminal"],
    preview: [
      "    ███    ",
      "  ██   ██  ",
      " ██ █ █ ██ ",
      "  ██   ██  ",
      "    ███    ",
    ].join("\n"),
  },
  {
    id: "gal-phosphor-badge",
    title: "Phosphor Badge",
    author: "gaab",
    charset: BLOCKS,
    cols: 13,
    rows: 5,
    tags: ["logo", "badge", "ui"],
    category: "logos",
    recipeId: "crt-green",
    collectionIds: ["col-featured"],
    preview: [
      "┌───────────┐",
      "│ ▓▓▓ ASCII │",
      "│ ░░ ENGINE │",
      "│ ▒▒ v3.0   │",
      "└───────────┘",
    ].join("\n"),
  },
  {
    id: "gal-face-soft",
    title: "Soft Face",
    author: "anon",
    charset: CLASSIC,
    cols: 13,
    rows: 7,
    tags: ["portrait", "face", "soft"],
    category: "portraits",
    recipeId: "ascii-portrait",
    collectionIds: ["col-featured"],
    preview: [
      "   .:::::.   ",
      "  ::o:::o::  ",
      "  :::::::::  ",
      "  :::\\_/:::  ",
      "   ':::::'   ",
      "     '''     ",
      "             ",
    ].join("\n"),
  },
  {
    id: "gal-horizon",
    title: "Horizon Line",
    author: "studio",
    charset: CLASSIC,
    cols: 24,
    rows: 6,
    tags: ["landscape", "sky", "calm"],
    category: "landscapes",
    recipeId: "low-contrast",
    collectionIds: ["col-terminal"],
    preview: [
      "          .  *     .    ",
      "    *           .       ",
      "~~~~~~~~~~~~~~~~~~~~~~~~",
      "########################",
      "@@@@@@@@@@@@@@@@@@@@@@@@",
      "%%%%%%%%%%%%%%%%%%%%%%%%",
    ].join("\n"),
  },
  {
    id: "gal-mountains",
    title: "Peak Range",
    author: "gaab",
    charset: CLASSIC,
    cols: 21,
    rows: 6,
    tags: ["landscape", "mountains"],
    category: "landscapes",
    recipeId: "sketch",
    collectionIds: ["col-dense"],
    preview: [
      "         /\\             ",
      "        /  \\    /\\      ",
      "   /\\  /    \\  /  \\     ",
      "  /  \\/      \\/    \\    ",
      " /    \\      /      \\   ",
      "/______\\____/________\\  ",
    ].join("\n"),
  },
  {
    id: "gal-checker",
    title: "Checker Field",
    author: "studio",
    charset: BLOCKS,
    cols: 16,
    rows: 8,
    tags: ["pattern", "grid", "dense"],
    category: "patterns",
    recipeId: "ascii-pixel",
    collectionIds: ["col-dense"],
    preview: Array.from({ length: 8 }, (_, y) =>
      Array.from({ length: 16 }, (_, x) => ((x + y) % 2 === 0 ? "█" : "░")).join(""),
    ).join("\n"),
  },
  {
    id: "gal-wave-matrix",
    title: "Wave Matrix",
    author: "anon",
    charset: DENSE,
    cols: 20,
    rows: 8,
    tags: ["pattern", "wave", "math"],
    category: "patterns",
    recipeId: "matrix",
    collectionIds: ["col-dense", "col-featured"],
    preview: (() => {
      const chars = " .:-=+*#%@";
      const lines: string[] = [];
      for (let y = 0; y < 8; y += 1) {
        let line = "";
        for (let x = 0; x < 20; x += 1) {
          const n = Math.sin(x * 0.45 + y * 0.35) * Math.cos(y * 0.25);
          const idx = Math.floor(((n + 1) * 0.5) * (chars.length - 1));
          line += chars[idx];
        }
        lines.push(line);
      }
      return lines.join("\n");
    })(),
  },
  {
    id: "gal-type-hello",
    title: "HELLO",
    author: "studio",
    charset: CLASSIC,
    cols: 29,
    rows: 5,
    tags: ["typography", "banner"],
    category: "typography",
    recipeId: "high-contrast",
    collectionIds: ["col-terminal"],
    preview: [
      "█ █ ████ █   █    ████",
      "█ █ █    █   █    █  █",
      "███ ███  █   █    █  █",
      "█ █ █    █   █    █  █",
      "█ █ ████ ████████ ████",
    ].join("\n"),
  },
  {
    id: "gal-type-ascii",
    title: "ASCII Wordmark",
    author: "gaab",
    charset: CLASSIC,
    cols: 27,
    rows: 3,
    tags: ["typography", "wordmark"],
    category: "typography",
    recipeId: "terminal",
    collectionIds: ["col-featured"],
    preview: [
      " ▄▄▄  ▄▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ",
      "█▄▄█ █▄▄▄▄ █   ▄█  ▄█  ",
      "█  █ ▄▄▄▄█ █▄▄ █▄▄ █▄▄ ",
    ].join("\n"),
  },
  {
    id: "gal-spiral",
    title: "Spiral Noise",
    author: "anon",
    charset: CLASSIC,
    cols: 15,
    rows: 9,
    tags: ["abstract", "noise", "spiral"],
    category: "abstract",
    recipeId: "cyberpunk",
    collectionIds: ["col-dense"],
    preview: [
      "·····#####·····",
      "···##·····##···",
      "··#···###···#··",
      "·#···#···#···#·",
      "·#··#··@··#··#·",
      "·#···#···#···#·",
      "··#···###···#··",
      "···##·····##···",
      "·····#####·····",
    ].join("\n"),
  },
  {
    id: "gal-cat",
    title: "Terminal Cat",
    author: "studio",
    charset: CLASSIC,
    cols: 15,
    rows: 7,
    tags: ["animal", "cat", "cute"],
    category: "animals",
    recipeId: "anime",
    collectionIds: ["col-featured", "col-terminal"],
    preview: [
      " /\\_/\\         ",
      "( o.o )  meow  ",
      " > ^ <         ",
      " /   \\   ~~    ",
      "(     )        ",
      " \\___/         ",
      "               ",
    ].join("\n"),
  },
  {
    id: "gal-hud-panel",
    title: "HUD Panel",
    author: "gaab",
    charset: CLASSIC,
    cols: 22,
    rows: 8,
    tags: ["ui", "hud", "panel"],
    category: "ui",
    recipeId: "crt-amber",
    collectionIds: ["col-terminal"],
    preview: [
      "╔════════════════════╗",
      "║ STATUS  · ONLINE   ║",
      "║ FPS     · 60       ║",
      "║ CELLS   · 12.4k    ║",
      "║────────────────────║",
      "║ [RUN]  [STOP] [··] ║",
      "║ ▓▓▓▓▓▓▓▓░░░░ 72%   ║",
      "╚════════════════════╝",
    ].join("\n"),
  },
  {
    id: "gal-matrix-cells",
    title: "Cell Grid",
    author: "studio",
    charset: CLASSIC,
    cols: 12,
    rows: 6,
    tags: ["ui", "grid", "matrix"],
    category: "ui",
    recipeId: "ibm-terminal",
    collectionIds: ["col-dense"],
    /** Matriz explícita — valida GalleryPreview union. */
    preview: [
      ["+", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "+"],
      ["|", " ", "A", " ", "B", " ", "C", " ", "D", " ", " ", "|"],
      ["|", " ", "E", " ", "F", " ", "G", " ", "H", " ", " ", "|"],
      ["|", " ", "I", " ", "J", " ", "K", " ", "L", " ", " ", "|"],
      ["|", " ", ".", " ", ".", " ", ".", " ", ".", " ", " ", "|"],
      ["+", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "+"],
    ],
  },
];

export const MOCK_GALLERY_COLLECTIONS: GalleryCollection[] = [
  {
    id: "col-featured",
    title: "Featured",
    description: "Destaques curados do Studio",
    itemIds: MOCK_GALLERY_ITEMS.filter((i) => i.collectionIds?.includes("col-featured")).map(
      (i) => i.id,
    ),
  },
  {
    id: "col-terminal",
    title: "Terminal Classics",
    description: "Estética phosphor / CRT",
    itemIds: MOCK_GALLERY_ITEMS.filter((i) => i.collectionIds?.includes("col-terminal")).map(
      (i) => i.id,
    ),
  },
  {
    id: "col-dense",
    title: "Dense Patterns",
    description: "Grids, waves e ruído",
    itemIds: MOCK_GALLERY_ITEMS.filter((i) => i.collectionIds?.includes("col-dense")).map(
      (i) => i.id,
    ),
  },
];
