import type { AsciiRecipe } from "@/features/ascii-engine/recipes/types";
import { IMAGE_CHARSETS } from "@/features/ascii-interaction/image-pipeline/charset-mapper";

const CLASSIC = IMAGE_CHARSETS.classic!;
const DENSE = IMAGE_CHARSETS.dense!;
const BLOCKS = IMAGE_CHARSETS.blocks!;
const UNICODE = IMAGE_CHARSETS.unicode!;
const BINARY = " 01";
const SKETCH = " .'`^\",:;Il!i><~+_-?][}{1)(|\\/tfjrxnuvczXYUJCLQ0OZmwqpdbkhao*#MW&8%B@$";
const MANGA = "　・‥…━┃┏┓┗┛╋░▒▓█";
const PIXEL = " ░▒▓█";

function recipe(
  partial: Omit<AsciiRecipe, "schemaVersion" | "createdAt" | "kind"> & { createdAt?: string },
): AsciiRecipe {
  return {
    ...partial,
    schemaVersion: 2,
    kind: "recipe",
    createdAt: partial.createdAt ?? "2026-07-10T00:00:00.000Z",
    rendererId: partial.rendererId ?? "canvas",
    defaultExporter: partial.defaultExporter ?? "html",
  };
}

/**
 * Packs product-facing — ≥20 receitas built-in (mesmo schema v2 dos presets).
 */
export const BUILTIN_RECIPES: AsciiRecipe[] = [
  recipe({
    id: "crt-green",
    name: "CRT Green",
    category: "terminal",
    description: "Fósforo verde clássico de monitor CRT.",
    tags: ["crt", "retro", "mono"],
    charset: CLASSIC,
    mappingMode: "brightness",
    algorithm: "brightness",
    dithering: "floyd-steinberg",
    colorMode: "crt-green",
    colors: "crt-green",
    gamma: 1.15,
    contrast: 1.25,
    brightness: 0.05,
    themeId: "crt",
    effects: ["noise"],
    defaultExporter: "html",
  }),
  recipe({
    id: "crt-amber",
    name: "CRT Amber",
    category: "terminal",
    description: "Monitor âmbar — leitura noturna vintage.",
    tags: ["crt", "amber", "retro"],
    charset: CLASSIC,
    mappingMode: "brightness",
    dithering: "atkinson",
    colorMode: "gradient",
    gamma: 1.1,
    contrast: 1.2,
    brightness: 0,
    themeId: "amber",
    effects: ["noise"],
    defaultExporter: "png",
  }),
  recipe({
    id: "ibm-terminal",
    name: "IBM Terminal",
    category: "terminal",
    description: "Terminal azul IBM 3270.",
    tags: ["ibm", "terminal"],
    charset: CLASSIC,
    mappingMode: "brightness",
    dithering: "ordered",
    colorMode: "ansi16",
    gamma: 1,
    contrast: 1.15,
    brightness: 0,
    themeId: "ibm",
    effects: [],
    defaultExporter: "ansi",
  }),
  recipe({
    id: "gameboy",
    name: "GameBoy",
    category: "retro",
    description: "Paleta 4 tons verde Game Boy.",
    tags: ["gameboy", "pixel"],
    charset: BLOCKS,
    mappingMode: "density",
    dithering: "bayer",
    colorMode: "ansi16",
    gamma: 1.2,
    contrast: 1.4,
    brightness: -0.05,
    themeId: "gameboy",
    effects: [],
    defaultExporter: "png",
    pipeline: { width: 80 },
  }),
  recipe({
    id: "matrix",
    name: "Matrix",
    category: "terminal",
    description: "Chuva digital — charset binário + gradient.",
    tags: ["matrix", "cyber"],
    charset: BINARY,
    mappingMode: "brightness",
    dithering: "ordered",
    colorMode: "gradient",
    gamma: 0.95,
    contrast: 1.3,
    brightness: 0,
    themeId: "matrix",
    effects: ["matrix"],
    defaultExporter: "html",
  }),
  recipe({
    id: "blueprint",
    name: "Blueprint",
    category: "art",
    description: "Traço técnico — edges + contraste alto.",
    tags: ["blueprint", "edge"],
    charset: CLASSIC,
    mappingMode: "edge",
    dithering: "none",
    colorMode: "truecolor",
    gamma: 1,
    contrast: 1.5,
    brightness: 0.1,
    themeId: "ibm",
    effects: [],
    defaultExporter: "svg",
    pipeline: { edgeEnhance: 1 },
  }),
  recipe({
    id: "cyberpunk",
    name: "Cyberpunk",
    category: "art",
    description: "Neon truecolor + dithering agressivo.",
    tags: ["cyber", "neon"],
    charset: UNICODE,
    mappingMode: "hybrid",
    dithering: "sierra",
    colorMode: "truecolor",
    gamma: 0.85,
    contrast: 1.35,
    brightness: 0.08,
    themeId: "crt-green",
    effects: ["particle-field"],
    defaultExporter: "png",
    pipeline: { sharpness: 0.35, width: 140 },
  }),
  recipe({
    id: "ansi",
    name: "ANSI",
    category: "terminal",
    description: "Paleta ANSI 16 cores para BBS/ANSI art.",
    tags: ["ansi", "bbs"],
    charset: DENSE,
    mappingMode: "brightness",
    dithering: "floyd-steinberg",
    colorMode: "ansi16",
    gamma: 1,
    contrast: 1.1,
    brightness: 0,
    themeId: "dos",
    effects: [],
    defaultExporter: "ansi",
  }),
  recipe({
    id: "dos",
    name: "DOS",
    category: "terminal",
    description: "Prompt DOS monocromático.",
    tags: ["dos", "retro"],
    charset: CLASSIC,
    mappingMode: "brightness",
    dithering: "none",
    colorMode: "mono",
    gamma: 1,
    contrast: 1.2,
    brightness: 0,
    themeId: "dos",
    effects: [],
    defaultExporter: "txt",
  }),
  recipe({
    id: "linux",
    name: "Linux",
    category: "terminal",
    description: "Terminal Linux moderno (teal accent).",
    tags: ["linux", "terminal"],
    charset: CLASSIC,
    mappingMode: "brightness",
    dithering: "floyd-steinberg",
    colorMode: "truecolor",
    gamma: 1,
    contrast: 1.05,
    brightness: 0,
    themeId: "linux",
    effects: [],
    defaultExporter: "html",
  }),
  recipe({
    id: "windows-terminal",
    name: "Windows Terminal",
    category: "terminal",
    description: "Look Windows Terminal / XP panel.",
    tags: ["windows", "terminal"],
    charset: CLASSIC,
    mappingMode: "brightness",
    dithering: "atkinson",
    colorMode: "truecolor",
    gamma: 1,
    contrast: 1.1,
    brightness: 0.02,
    themeId: "windows-xp",
    effects: [],
    defaultExporter: "html",
  }),
  recipe({
    id: "ascii-portrait",
    name: "ASCII Portrait",
    category: "art",
    description: "Retrato fotográfico — FS dither + CRT Green.",
    tags: ["portrait", "photo"],
    charset: UNICODE,
    mappingMode: "brightness",
    dithering: "floyd-steinberg",
    colorMode: "crt-green",
    gamma: 1,
    contrast: 1.1,
    brightness: 0,
    themeId: "crt-green",
    effects: [],
    defaultExporter: "png",
    pipeline: { width: 100 },
  }),
  recipe({
    id: "ascii-manga",
    name: "ASCII Manga",
    category: "art",
    description: "Traço manga — edges + charset denso.",
    tags: ["manga", "anime"],
    charset: MANGA,
    mappingMode: "edge",
    dithering: "none",
    colorMode: "mono",
    gamma: 1.05,
    contrast: 1.45,
    brightness: 0.05,
    themeId: "monochrome",
    effects: [],
    defaultExporter: "svg",
    pipeline: { edgeEnhance: 0.85, invert: false },
  }),
  recipe({
    id: "ascii-pixel",
    name: "ASCII Pixel",
    category: "art",
    description: "Blocos pixel — ordered dither.",
    tags: ["pixel", "blocks"],
    charset: PIXEL,
    mappingMode: "density",
    dithering: "ordered",
    colorMode: "truecolor",
    gamma: 1.1,
    contrast: 1.25,
    brightness: 0,
    themeId: "crt-green",
    effects: [],
    defaultExporter: "png",
    pipeline: { width: 64, fontCompensation: 1 },
  }),
  recipe({
    id: "ascii-sketch",
    name: "ASCII Sketch",
    category: "art",
    description: "Esboço a lápis — hybrid + soft gamma.",
    tags: ["sketch", "art"],
    charset: SKETCH,
    mappingMode: "hybrid",
    dithering: "atkinson",
    colorMode: "mono",
    gamma: 1.25,
    contrast: 0.95,
    brightness: 0.1,
    themeId: "monochrome",
    effects: [],
    defaultExporter: "svg",
  }),
  recipe({
    id: "low-contrast",
    name: "Low Contrast",
    category: "tone",
    description: "Tons suaves — contraste baixo.",
    tags: ["tone", "soft"],
    charset: CLASSIC,
    mappingMode: "brightness",
    dithering: "floyd-steinberg",
    colorMode: "truecolor",
    gamma: 1.1,
    contrast: 0.7,
    brightness: 0.08,
    themeId: "linux",
    effects: [],
    defaultExporter: "html",
  }),
  recipe({
    id: "high-contrast",
    name: "High Contrast",
    category: "tone",
    description: "Punch máximo — contraste e threshold.",
    tags: ["tone", "punch"],
    charset: DENSE,
    mappingMode: "brightness",
    dithering: "none",
    colorMode: "mono",
    gamma: 0.9,
    contrast: 1.8,
    brightness: 0,
    themeId: "monochrome",
    effects: [],
    defaultExporter: "txt",
    pipeline: { threshold: 0.15 },
  }),
  recipe({
    id: "noir",
    name: "Noir",
    category: "tone",
    description: "Filme noir — invert + mono.",
    tags: ["noir", "film"],
    charset: UNICODE,
    mappingMode: "brightness",
    dithering: "jarvis",
    colorMode: "mono",
    gamma: 1.2,
    contrast: 1.4,
    brightness: -0.1,
    themeId: "monochrome",
    effects: ["smoke"],
    defaultExporter: "png",
    pipeline: { invert: true },
  }),
  recipe({
    id: "retro-monitor",
    name: "Retro Monitor",
    category: "terminal",
    description: "CRT largo + blur leve.",
    tags: ["crt", "retro"],
    charset: CLASSIC,
    mappingMode: "brightness",
    dithering: "floyd-steinberg",
    colorMode: "crt-green",
    gamma: 1.2,
    contrast: 1.3,
    brightness: 0,
    themeId: "crt",
    effects: ["noise"],
    defaultExporter: "html",
    pipeline: { width: 80, blur: 0.3 },
  }),
  recipe({
    id: "anime",
    name: "Anime",
    category: "art",
    description: "Cel-shading ASCII — truecolor + edges.",
    tags: ["anime", "cel"],
    charset: UNICODE,
    mappingMode: "hybrid",
    dithering: "stucki",
    colorMode: "truecolor",
    gamma: 0.95,
    contrast: 1.2,
    brightness: 0.05,
    themeId: "crt-green",
    effects: [],
    defaultExporter: "png",
    pipeline: { edgeEnhance: 0.4, sharpness: 0.25, width: 120 },
  }),
  recipe({
    id: "terminal",
    name: "Terminal",
    category: "terminal",
    description: "Terminal genérico limpo.",
    tags: ["terminal", "default"],
    charset: CLASSIC,
    mappingMode: "brightness",
    dithering: "floyd-steinberg",
    colorMode: "crt-green",
    gamma: 1,
    contrast: 1,
    brightness: 0,
    themeId: "crt-green",
    effects: [],
    defaultExporter: "txt",
  }),
  recipe({
    id: "sketch",
    name: "Sketch",
    category: "art",
    description: "Sketch rápido — charset curto.",
    tags: ["sketch"],
    charset: " .,:;-+*=%#@",
    mappingMode: "edge",
    dithering: "none",
    colorMode: "mono",
    gamma: 1.15,
    contrast: 1.2,
    brightness: 0.05,
    themeId: "monochrome",
    effects: [],
    defaultExporter: "svg",
    pipeline: { edgeEnhance: 0.7 },
  }),
  recipe({
    id: "pixel-art",
    name: "Pixel Art",
    category: "art",
    description: "Pixel art baixa resolução.",
    tags: ["pixel"],
    charset: BLOCKS,
    mappingMode: "density",
    dithering: "bayer",
    colorMode: "ansi256",
    gamma: 1,
    contrast: 1.15,
    brightness: 0,
    themeId: "gameboy",
    effects: [],
    defaultExporter: "png",
    pipeline: { width: 48, fontCompensation: 1 },
  }),
  recipe({
    id: "phosphor",
    name: "Phosphor",
    category: "terminal",
    description: "Fósforo CRT Green — look de produto.",
    tags: ["phosphor", "brand"],
    charset: CLASSIC,
    mappingMode: "brightness",
    dithering: "floyd-steinberg",
    colorMode: "crt-green",
    gamma: 1.05,
    contrast: 1.15,
    brightness: 0.02,
    themeId: "crt-green",
    effects: ["matrix"],
    defaultExporter: "html",
  }),
];
