import type { BrushPreset } from "@/features/ascii-engine/brush/types";

const BASE = {
  charsetMode: "density" as const,
  colors: [{ r: 0, g: 255, b: 100 }],
  opacitySim: 1,
  scatter: 0,
  spacing: 0.35,
  rotation: 0,
  flow: 1,
  hardness: 0.85,
  blendMode: "normal" as const,
  randomization: 0,
};

export const BRUSH_PRESETS: BrushPreset[] = [
  {
    ...BASE,
    id: "pencil",
    name: "Pencil",
    kind: "pencil",
    status: "ready",
    charset: "#",
    charsetMode: "fixed",
    size: 1,
    density: 1,
    hardness: 1,
  },
  {
    ...BASE,
    id: "brush",
    name: "Brush",
    kind: "brush",
    status: "ready",
    charset: " .:-=+*#%@",
    size: 3,
    density: 0.85,
    hardness: 0.7,
  },
  {
    ...BASE,
    id: "spray",
    name: "Spray",
    kind: "spray",
    status: "ready",
    charset: "·•*oO@",
    size: 5,
    density: 0.35,
    scatter: 0.6,
    hardness: 0.3,
    randomization: 0.4,
  },
  {
    ...BASE,
    id: "airbrush",
    name: "Airbrush",
    kind: "airbrush",
    status: "ready",
    charset: " .:-=+",
    size: 7,
    density: 0.25,
    scatter: 0.2,
    hardness: 0.15,
    flow: 0.4,
  },
  {
    ...BASE,
    id: "noise",
    name: "Noise",
    kind: "noise",
    status: "experimental",
    charset: "░▒▓█",
    size: 4,
    density: 0.5,
    randomization: 0.8,
    scatter: 0.3,
  },
  {
    ...BASE,
    id: "matrix",
    name: "Matrix",
    kind: "matrix",
    status: "experimental",
    charset: "01アイウエオカキクケコ",
    colors: [{ r: 0, g: 220, b: 70 }],
    size: 2,
    density: 0.7,
    randomization: 0.5,
  },
  {
    ...BASE,
    id: "fire",
    name: "Fire",
    kind: "fire",
    status: "experimental",
    charset: " .'`^\"*,:;Il!i~+_-?][}{1)(|/tfjrxnuvczXYUJCLQ0OZmwqpdbkhao*#MW&8%B@$",
    colors: [
      { r: 255, g: 80, b: 0 },
      { r: 255, g: 200, b: 40 },
    ],
    size: 4,
    density: 0.6,
    scatter: 0.25,
    randomization: 0.35,
  },
  {
    ...BASE,
    id: "smoke",
    name: "Smoke",
    kind: "smoke",
    status: "experimental",
    charset: " .:-=+*#",
    colors: [{ r: 160, g: 160, b: 170 }],
    size: 6,
    density: 0.3,
    scatter: 0.4,
    hardness: 0.2,
  },
  {
    ...BASE,
    id: "rain",
    name: "Rain",
    kind: "rain",
    status: "experimental",
    charset: "|/\\'",
    charsetMode: "random",
    colors: [{ r: 120, g: 180, b: 255 }],
    size: 3,
    density: 0.4,
    scatter: 0.5,
    randomization: 0.6,
  },
];

export function getBrushPreset(id: string): BrushPreset | undefined {
  return BRUSH_PRESETS.find((p) => p.id === id);
}

export function listBrushPresets(status?: BrushPreset["status"]): BrushPreset[] {
  if (!status) return [...BRUSH_PRESETS];
  return BRUSH_PRESETS.filter((p) => p.status === status);
}
